[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "senate-hearings"
version = "0.1.0"
description = "Scrape and clean U.S. Senate hearing transcripts."
readme = "README.md"
requires-python = ">=3.11,<3.13"
license = { text = "MIT" }
authors = [
  { name = "Mikkel Christensen" },
  { name = "Corbin Brinkerhoff" }
]
keywords = ["scraping", "nlp", "senate", "transcripts", "streamlit", "quarto"]
dependencies = [
    "beautifulsoup4>=4.12.0",
    "ipykernel>=7.1.0",
    "nbclient>=0.10.2",
    "nbformat>=5.10.4",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "playwright>=1.55.0",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
    "selenium>=4.38.0",
    "streamlit>=1.52.1",
]

[project.optional-dependencies]
dev = [
  "spacy>=3.8.11",
  "sentence-transformers>=5.2.0",
  
]

[project.urls]
Homepage = "https://github.com/lmikkelc5/senate-hearings"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
